services:
  banner_api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./banner_api:/opt/app
    networks:
      - local

  dramatiq:
    build: .
    entrypoint: ./dramatiq-entrypoint.sh
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./banner_api:/opt/app
    networks:
      - local

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 5s
    networks:
      - local

  redis:
    image: redis:latest
    restart: always
    expose:
      - 6379
    networks:
      - local

volumes:
  db:


networks:
  local:
